replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: latest

# Secrets for pulling an image from a private repository
imagePullSecrets: []
# Override the chart name.
nameOverride: ""
fullnameOverride: ""

command: null
args: null

# List of Dicts of key value environment variables
env: []
# Dictionary of key:value pairs, use this for simple environment variables
# so multiple configuration files can be merged (lists are overridden)
envDict: {}
# Environment variables taken from a ConfigMap or Secret
envFrom: []

serviceAccount:
  # Whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  # Annotations to add to the service account
  annotations: {}
  # Optionally override the name of the service account
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

extraFiles: {}
  # key1:
  #   mountPath: /path/to/file.txt
  #   text: |
  #     abcde
  #     12345

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

# https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# If pvc.create is true a PVC will be created and mounted,
# otherwise this section is ignored
pvc:
  create: false
  storageClassName:
  accessMode: ReadWriteOnce
  # Optionally override the name of the PVC
  name: ""
  # Size of the volume
  storage: 1Gi
  # Where to mount the PVC in the pod
  mountPath: /data

# Additional volumes on the deployment
volumes: []

# Additional volumeMounts on the deployment
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
