name: Build
on:
  push:
  pull_request:

env:
  CHART_NAME: generic-webservice
  COMMIT_USER: manics-bot
  VALIDATE_KUBERNETES_VERSION: "1.30.6"

jobs:

  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubeconform
        run: curl -sfL https://github.com/yannh/kubeconform/releases/download/v0.6.7/kubeconform-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - kubeconform

      - name: Lint
        run: |
          helm lint helm-chart/
          helm template helm-chart/ | kubeconform -strict -verbose -kubernetes-version "$VALIDATE_KUBERNETES_VERSION"

  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install K3s
        uses: jupyterhub/action-k3s-helm@v4
        with:
          k3s-channel: v1.32

      - name: Install chart
        run: |
          helm upgrade --install test ./helm-chart -f tests/test-config.yaml --set-file "extraFiles.key1.text=tests/file.txt" --wait

      - name: Test chart
        run: |
          helm test test
          curl -v http://localhost/srv/file.txt > file.txt
          diff --report-identical-files tests/file.txt file.txt

  publish:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    needs:
      - lint
      - test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Chart.yaml version with tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          yq eval ".version |= \"${{ github.ref_name }}"" helm-chart/Chart.yaml

      - name: Build chart
        run: |
          helm package helm-chart

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Add chart to gh-pages
        run: |
          shopt -s nullglob
          filename=(${CHART_NAME}-*.tgz)
          if [ -z "$filename" ]; then
            echo "No chart found"
            exit 1
          fi
          if [ -f "gh-pages/$filename" ]; then
            echo "Chart $filename already exists"
            exit 1
          fi
          mv "$filename" gh-pages/
          helm repo index gh-pages/

      - name: Commit gh-pages
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          git config user.name "$COMMIT_USER"
          git config user.email "${COMMIT_USER}@users.noreply.github.com"
          git add --all
          git commit -m "Update chart"
        working-directory: gh-pages

      - name: Push gh-pages
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          git push origin gh-pages
        working-directory: gh-pages
